const sendLogApiEvent = ['CLICK_SEND_MESSAGE', 'CLICK_PURCHASE'];

const appsFlyerEvent = {
  LOAD_LOGIN_SNS: 'LOAD_LOGIN_SNS',
  SUBMIT_SEARCH: 'SUBMIT_SEARCH',
  VIEW_PRODUCT_LIST: 'VIEW_PRODUCT_LIST',
  CLICK_PRODUCT_DETAIL: 'CLICK_PRODUCT_DETAIL',
  CLICK_PURCHASE: 'CLICK_PURCHASE',
  CLICK_WISH: 'CLICK_WISH'
};

const naverEvent = {
  CLICK_PURCHASE: 'CLICK_PURCHASE',
  CLICK_WISH: 'CLICK_WISH',
  VIEW_PRODUCT_LIST: 'VIEW_PRODUCT_LIST',
  VIEW_PRODUCT_DETAIL: 'VIEW_PRODUCT_DETAIL',
  CLICK_PRODUCT_DETAIL: 'CLICK_PRODUCT_DETAIL'
};

const commonEvent = {
  VIEW_ALL: 'VIEW_ALL',
  VIEW_MAIN: 'VIEW_MAIN',
  VIEW_SEARCH_MODAL: 'VIEW_SEARCH_MODAL',
  VIEW_PRODUCT_LIST: 'VIEW_PRODUCT_LIST',
  VIEW_WISH_LIST: 'VIEW_WISH_LIST',
  CLICK_WISH: 'CLICK_WISH',
  CLICK_WISH_CANCEL: 'CLICK_WISH_CANCEL',
  CLICK_TAB_SEARCH: 'CLICK_TAB_SEARCH',
  CLICK_LOGIN_SNS: 'CLICK_LOGIN_SNS',
  LOAD_LOGIN_SNS: 'LOAD_LOGIN_SNS',
  SELECT_ITEM: 'SELECT_ITEM',
  CLICK_NEXT_STEP1: 'CLICK_NEXT_STEP1',
  CLICK_NEXT_STEP2: 'CLICK_NEXT_STEP2',
  SELECT_MARKETING_POPUP: 'SELECT_MARKETING_POPUP',
  CLICK_SEARCHMODAL: 'CLICK_SEARCHMODAL',
  CLICK_RECENT: 'CLICK_RECENT',
  CLICK_PRODUCT_DETAIL: 'CLICK_PRODUCT_DETAIL',
  CLICK_PERSONAL_TAG: 'CLICK_PERSONAL_TAG',
  CLICK_PERSONAL_MORE: 'CLICK_PERSONAL_MORE',
  CLICK_RECOMMTAG: 'CLICK_RECOMMTAG',
  CLICK_POPC: 'CLICK_POPC',
  CLICK_RANK: 'CLICK_RANK',
  CLICK_AUTO: 'CLICK_AUTO',
  CLICK_RANKTAG: 'CLICK_RANKTAG',
  SUBMIT_SEARCH: 'SUBMIT_SEARCH',
  CLICK_AI_ON: 'CLICK_AI_ON',
  CLICK_REPORT: 'CLICK_REPORT',
  CLICK_REPORTSUBMIT: 'CLICK_REPORTSUBMIT',
  CLICK_PURCHASE: 'CLICK_PURCHASE',
  CLICK_PERSONALINPUT: 'CLICK_PERSONALINPUT',
  CLICK_PUSH_ON: 'CLICK_PUSH_ON',
  CLICK_PUSH_OFF: 'CLICK_PUSH_OFF',
  SELECT_LOGOUT: 'SELECT_LOGOUT',
  SELECT_WITHDRAW: 'SELECT_WITHDRAW',
  CLICK_LOGIN: 'CLICK_LOGIN',
  CLICK_KEYWORD_REQUEST: 'CLICK_KEYWORD_REQUEST',
  SCRIPT_ERROR: 'SCRIPT_ERROR',
  REQUEST_ERROR: 'REQUEST_ERROR',
  CLICK_HONEYNOTI: 'CLICK_HONEYNOTI',
  VIEW_HONEYNOTI_SEARCH: 'VIEW_HONEYNOTI_SEARCH',
  VIEW_HOT: 'VIEW_HOT',
  CLICK_TAB_HOT: 'CLICK_TAB_HOT',
  CLICK_TAB_CATEGORY: 'CLICK_TAB_CATEGORY',
  VIEW_HONEYNOTI_LIST: 'VIEW_HONEYNOTI_LIST',
  VIEW_BEHAVIOR_LIST: 'VIEW_BEHAVIOR_LIST',
  VIEW_HONEYNOTI_MANAGE: 'VIEW_HONEYNOTI_MANAGE',
  VIEW_HONEYNOTI_FILTER: 'VIEW_HONEYNOTI_FILTER',
  VIEW_CATEGORY: 'VIEW_CATEGORY',
  CLICK_CATEGORY: 'CLICK_CATEGORY',
  CLICK_APPLY_IDFILTER: 'CLICK_APPLY_IDFILTER',
  CLICK_BEHAVIOR_LIST: 'CLICK_BEHAVIOR_LIST',
  CLICK_HONEYNOTI_MANAGE: 'CLICK_HONEYNOTI_MANAGE',
  CLICK_NIGHT_ALARM: 'CLICK_NIGHT_ALARM',
  CLICK_PERSONAL_ALL: 'CLICK_PERSONAL_ALL',
  CLICK_PERSONAL_INPUT: 'CLICK_PERSONAL_INPUT',
  CLICK_PERSONAL_NEXT: 'CLICK_PERSONAL_NEXT',
  CLICK_TAB_MAIN: 'CLICK_TAB_MAIN',
  CLICK_TAB_MY: 'CLICK_TAB_MY',
  CLICK_TAB_WISH: 'CLICK_TAB_WISH',
  LOAD_PERSONAL_LIST: 'LOAD_PERSONAL_LIST',
  SELECT_ID_FILTER: 'SELECT_ID_FILTER',
  SELECT_MAP_FILTER: 'SELECT_MAP_FILTER',
  SUBMIT_PERSONAL_INPUT: 'SUBMIT_PERSONAL_INPUT',
  SUBMIT_SURVEY: 'SUBMIT_SURVEY',
  VIEW_FILTER: 'VIEW_FILTER',
  VIEW_HONEINOTI_FILTER: 'VIEW_HONEINOTI_FILTER',
  VIEW_ID_FILTER: 'VIEW_ID_FILTER',
  VIEW_MAP_FILTER: 'VIEW_MAP_FILTER',
  VIEW_PERSONAL_INPUT: 'VIEW_PERSONAL_INPUT',
  VIEW_PRODUCT_DETAIL: 'VIEW_PRODUCT_DETAIL',
  VIEW_RECENT_LIST: 'VIEW_RECENT_LIST',
  VIEW_SURVEY: 'VIEW_SURVEY',
  VIEW_WELCOME: 'VIEW_WELCOME',
  VIEW_ANNOUNCE_DETAIL: 'VIEW_ANNOUNCE_DETAIL',
  CLICK_CLOSE: 'CLICK_CLOSE',
  CLICK_BACK: 'CLICK_BACK',
  VIEW_HOTPRODUCT_TOOLTIP: 'VIEW_HOTPRODUCT_TOOLTIP',
  CLICK_LEGIT_BANNER: 'CLICK_LEGIT_BANNER',
  CLICK_LEGIT_MODAL: 'CLICK_LEGIT_MODAL',
  VIEW_LEGIT_INFO: 'VIEW_LEGIT_INFO',
  VIEW_LEGIT_SURVEY: 'VIEW_LEGIT_SURVEY',
  SUBMIT_LEGIT_SURVEY: 'SUBMIT_LEGIT_SURVEY',
  CLICK_MYLIST_FLOATING: 'CLICK_MYLIST_FLOATING',
  CLICK_MYLIST_AUTO: 'CLICK_MYLIST_AUTO'
};

const login = {
  LOAD_LOGIN_SNS: 'LOAD_LOGIN_SNS',
  CLICK_LOGIN_SNS: 'CLICK_LOGIN_SNS',
  CLICK_NONLOGIN: 'CLICK_NONLOGIN',
  VIEW_LOGIN: 'VIEW_LOGIN',
  SUBMIT_LOGIN_SNS: 'SUBMIT_LOGIN_SNS',
  CLICK_TAB: 'CLICK_TAB',
  CLICK_RECENT: 'CLICK_RECENT'
};

const brand = {
  VIEW_BRAND_LIST: 'VIEW_BRAND_LIST',
  CLICK_BRAND_SEARCH: 'CLICK_BRAND_SEARCH',
  CLICK_AUTO: 'CLICK_AUTO',
  CLICK_BRAND_NAME: 'CLICK_BRAND_NAME',
  CLICK_NAVIGATION_LETTER: 'CLICK_NAVIGATION_LETTER'
};

const search = {
  VIEW_SEARCH_MODAL: 'VIEW_SEARCH_MODAL',
  CLICK_BACK: 'CLICK_BACK',
  CLICK_RECOMMTAG: 'CLICK_RECOMMTAG',
  CLICK_KEYWORD_INPUT: 'CLICK_KEYWORD_INPUT',
  CLICK_SCOPE: 'CLICK_SCOPE',
  CLICK_RECENT_DELETE: 'CLICK_RECENT_DELETE',
  CLICK_RECENT: 'CLICK_RECENT',
  CLICK_BANNERB: 'CLICK_BANNERB',
  CLICK_AUTO: 'CLICK_AUTO',
  SUBMIT_SEARCH: 'SUBMIT_SEARCH',
  LOAD_KEYWORD_AUTO: 'LOAD_KEYWORD_AUTO',
  NOT_KEYWORD: 'NOT_KEYWORD',
  CLICK_MAIN_BUTTON: 'CLICK_MAIN_BUTTON',
  LOAD_MYLIST: 'LOAD_MYLIST',
  VIEW_RECOMMFILTER: 'VIEW_RECOMMFILTER',
  CLICK_RECOMMFILTER: 'CLICK_RECOMMFILTER'
};

const userInput = {
  VIEW_PERSONAL_INPUT: 'VIEW_PERSONAL_INPUT',
  SELECT_ITEM: 'SELECT_ITEM',
  SUBMIT_PERSONAL_INPUT: 'SUBMIT_PERSONAL_INPUT',
  CLICK_PERSONAL_INPUT: 'CLICK_PERSONAL_INPUT',
  CLICK_BACK: 'CLICK_BACK',
  CLICK_VIEW_ALL: 'CLICK_VIEW_ALL',
  CLICK_BRAND_DELETE: 'CLICK_BRAND_DELETE',
  VIEW_ANNOUNCE_DETAIL: 'VIEW_ANNOUNCE_DETAIL'
};

const mypage = {
  VIEW_MY: 'VIEW_MY',
  SELECT_LOGOUT: 'SELECT_LOGOUT',
  SELECT_WITHDRAW: 'SELECT_WITHDRAW',
  CLICK_LOGOUT: 'CLICK_LOGOUT',
  CLICK_WITHDRAW: 'CLICK_WITHDRAW',
  CLICK_PUSH_ON: 'CLICK_PUSH_ON',
  CLICK_PUSH_OFF: 'CLICK_PUSH_OFF',
  CLICK_NIGHT_ALARM: 'CLICK_NIGHT_ALARM',
  CLICK_LOGIN: 'CLICK_LOGIN',
  CLICK_KAKAOCH: 'CLICK_KAKAOCH',
  CLICK_ANNOUNCE_DETAIL: 'CLICK_ANNOUNCE_DETAIL',
  CLICK_PERSONAL_INPUT: 'CLICK_PERSONAL_INPUT'
};

const header = {
  CLICK_LOGO: 'CLICK_LOGO',
  CLICK_BACK: 'CLICK_BACK',
  CLICK_SCOPE: 'CLICK_SCOPE',
  CLICK_SEARCHMODAL: 'CLICK_SEARCHMODAL',
  CLICK_CLOSE: 'CLICK_CLOSE'
};

const wishes = {
  VIEW_WISH_LIST: 'VIEW_WISH_LIST',
  CLICK_SORT: 'CLICK_SORT',
  CLICK_CATEGORY: 'CLICK_CATEGORY',
  CLICK_PRODUCT_DETAIL: 'CLICK_PRODUCT_DETAIL',
  CLICK_WISH_CANCEL: 'CLICK_WISH_CANCEL',
  VIEW_RECENT_LIST: 'VIEW_RECENT_LIST',
  CLICK_SEARCHMODAL: 'CLICK_SEARCHMODAL',
  SELECT_SORT: 'SELECT_SORT',
  CLICK_LOGIN: 'CLICK_LOGIN',
  CLICK_RECENT: 'CLICK_RECENT',
  VIEW_HOTPRODUCT_TOOLTIP: 'VIEW_HOTPRODUCT_TOOLTIP',
  VIEW_PRODUCT_DETAIL_TOOLTIP: 'VIEW_PRODUCT_DETAIL_TOOLTIP'
};

const noti = {
  VIEW_BEHAVIOR_LIST: 'VIEW_BEHAVIOR_LIST',
  CLICK_BEHAVIOR: 'CLICK_BEHAVIOR',
  VIEW_HONEYNOTI_LIST: 'VIEW_HONEYNOTI_LIST',
  CLICK_HONEYNOTI_MANAGE: 'CLICK_HONEYNOTI_MANAGE',
  CLICK_PRODUCT_DETAIL: 'CLICK_PRODUCT_DETAIL'
};

const sellerInfo = {
  CLICK_PRODUCT_DETAIL: 'CLICK_PRODUCT_DETAIL',
  VIEW_SELLER_PRODUCT: 'VIEW_SELLER_PRODUCT',
  VIEW_SELLER_REVIEW: 'VIEW_SELLER_REVIEW',
  LOAD_MOREAUTO: 'LOAD_MOREAUTO',
  CLICK_SELLER_PRODUCT: 'CLICK_SELLER_PRODUCT',
  CLICK_SELLER_REVIEW: 'CLICK_SELLER_REVIEW'
};

const productsKeyword = {
  CLICK_PRODUCT_LIST: 'CLICK_PRODUCT_LIST',
  CLICK_MYLIST: 'CLICK_MYLIST',
  CLICK_UNDO: 'CLICK_UNDO',
  VIEW_MYLIST: 'VIEW_MYLIST'
};

const category = {
  CLICK_CATEGORY_GENDER: 'CLICK_CATEGORY_GENDER',
  CLICK_CATEGORY: 'CLICK_CATEGORY',
  VIEW_CATEGORY: 'VIEW_CATEGORY',
  CLICK_BRAND_NAME: 'CLICK_BRAND_NAME',
  CLICK_BRAND_LIST: 'CLICK_BRAND_LIST'
};

const home = {
  VIEW_MAIN: 'VIEW_MAIN',
  VIEW_MAIN_PC: 'VIEW_MAIN_PC',
  CLICK_SEARCHMODAL: 'CLICK_SEARCHMODAL',
  CLICK_BEHAVIOR_LIST: 'CLICK_BEHAVIOR_LIST',
  CLICK_RECENT: 'CLICK_RECENT',
  CLICK_MAIN: 'CLICK_MAIN',
  CLICK_MAIN_BRAND: 'CLICK_MAIN_BRAND',
  CLICK_MAIN_CATEGORY: 'CLICK_MAIN_CATEGORY',
  VIEW_ALL: 'VIEW_ALL',
  CLICK_WISH_CANCEL: 'CLICK_WISH_CANCEL',
  CLICK_WISH: 'CLICK_WISH',
  CLICK_PRODUCT_DETAIL: 'CLICK_PRODUCT_DETAIL',
  CLICK_PRODUCT_LIST: 'CLICK_PRODUCT_LIST',
  SWIPE_X_TAG: 'SWIPE_X_TAG',
  SWIPE_X_BRAND: 'SWIPE_X_BRAND',
  CLICK_PERSONAL_ALL: 'CLICK_PERSONAL_ALL',
  VIEW_WISHPRICE_TOOLTIP: 'VIEW_WISHPRICE_TOOLTIP',
  CLICK_LEGIT_ROLLING: 'CLICK_LEGIT_ROLLING',
  CLICK_RECENT_BUTTON: 'CLICK_RECENT_BUTTON',
  CLICK_MYLIST_BUTTON: 'CLICK_MYLIST_BUTTON',
  VIEW_WISHPRODUCT: 'VIEW_WISHPRODUCT',
  VIEW_MYLIST: 'VIEW_MYLIST',
  LOAD_MYLIST: 'LOAD_MYLIST',
  SWIPE_X_BUTTON: 'SWIPE_X_BUTTON',
  SWIP_X_CARD: 'SWIP_X_CARD',
  CLICK_MAIN_BUTTON: 'CLICK_MAIN_BUTTON'
};

const products = {
  VIEW_PRODUCT_LIST: 'VIEW_PRODUCT_LIST',
  LOAD_PRODUCT_LIST: 'LOAD_PRODUCT_LIST',
  LOAD_MOREAUTO: 'LOAD_MOREAUTO',
  VIEW_FILTER: 'VIEW_FILTER',
  SWIPE_X_FILTER: 'SWIPE_X_FILTER',
  CLICK_APPLYFILTER: 'CLICK_APPLYFILTER',
  CLICK_RESETALL: 'CLICK_RESETALL',
  SELECT_FILTER: 'SELECT_FILTER',
  CLICK_FILTER_DELETE: 'CLICK_FILTER_DELETE',
  CLICK_FILTER: 'CLICK_FILTER',
  SELECT_FILTERTAB: 'SELECT_FILTERTAB',
  CLICK_APPLY_IDFILTER: 'CLICK_APPLY_IDFILTER',
  SELECT_ID_FILTER: 'SELECT_ID_FILTER',
  VIEW_MAP_FILTER: 'VIEW_MAP_FILTER',
  CLICK_PERSONAL_INPUT: 'CLICK_PERSONAL_INPUT',
  SELECT_MAP_FILTER: 'SELECT_MAP_FILTER',
  CLICK_SORT: 'CLICK_SORT',
  SELECT_SORT: 'SELECT_SORT',
  CLICK_BRAND_REQUEST: 'CLICK_BRAND_REQUEST',
  CLICK_KEYWORD_REQUEST: 'CLICK_KEYWORD_REQUEST',
  CLICK_LOGIN: 'CLICK_LOGIN',
  CLICK_APPLY_MAPFILTER: 'CLICK_APPLY_MAPFILTER',
  VIEW_MYFILTER_TOOLTIP: 'VIEW_MYFILTER_TOOLTIP',
  CLICK_MYFILTER: 'CLICK_MYFILTER',
  VIEW_MYLIST_MODAL: 'VIEW_MYLIST_MODAL',
  VIEW_MYLIST_POPUP: 'VIEW_MYLIST_POPUP',
  CLICK_MYLIST_MODAL: 'CLICK_MYLIST_MODAL',
  CLICK_MYLIST: 'CLICK_MYLIST',
  CLICK_BACK: 'CLICK_BACK',
  VIEW_MYLIST: 'VIEW_MYLIST',
  VIEW_MYFILTER: 'VIEW_MYFILTER',
  VIEW_RECOMMPRICE: 'VIEW_RECOMMPRICE',
  CLICK_RECOMMPRICE: 'CLICK_RECOMMPRICE',
  CLICK_BRAND_SEARCH: 'CLICK_BRAND_SEARCH',
  CLICK_UNDO: 'CLICK_UNDO',
  VIEW_PRODUCT_DETAIL: 'VIEW_PRODUCT_DETAIL',
  CLICK_PURCHASE: 'CLICK_PURCHASE',
  CLICK_SELLER_REVIEW: 'CLICK_SELLER_REVIEW',
  CLICK_SHARE: 'CLICK_SHARE',
  CLICK_REPORT: 'CLICK_REPORT',
  SELECT_REPORT: 'SELECT_REPORT',
  CLICK_REPORTSUBMIT: 'CLICK_REPORTSUBMIT',
  CLICK_SELLER_PRODUCT: 'CLICK_SELLER_PRODUCT',
  CLICK_RECENT: 'CLICK_RECENT',
  CLICK_PIC: 'CLICK_PIC',
  VIEW_PICGALLERY: 'VIEW_PICGALLERY',
  SWIPE_X_PIC: 'SWIPE_X_PIC',
  CLICK_PICGALLERY_CLOSE: 'CLICK_PICGALLERY_CLOSE',
  CLICK_PRODUCT_DETAIL: 'CLICK_PRODUCT_DETAIL',
  CLICK_EXPAND: 'CLICK_EXPAND',
  CLICK_WISH: 'CLICK_WISH',
  CLICK_WISH_CANCEL: 'CLICK_WISH_CANCEL',
  CLICK_WISHMOAL_CLOSE: 'CLICK_WISHMOAL_CLOSE',
  VIEW_WISH_MODAL: 'VIEW_WISH_MODAL',
  CLICK_SEARCHMODAL: 'CLICK_SEARCHMODAL',
  CLICK_WISH_LIST: 'CLICK_WISH_LIST',
  SELLER_PRODUCT: 'SELLER_PRODUCT',
  SWIP_X_CARD: 'SWIP_X_CARD',
  VIEW_PRODUCT_DETAIL_TOAST: 'VIEW_PRODUCT_DETAIL_TOAST',
  VIEW_PURCHASE_TOOLTIP: 'VIEW_PURCHASE_TOOLTIP',
  VIEW_WISHPRICE_TOOLTIP: 'VIEW_WISHPRICE_TOOLTIP',
  CLICK_CLOSE: 'CLICK_CLOSE',
  VIEW_APPREVIEW_PROMPT: 'VIEW_APPREVIEW_PROMPT',
  CLICK_MYLIST_FLOATING: 'CLICK_MYLIST_FLOATING',
  CLICK_MYLIST_AUTO: 'CLICK_MYLIST_AUTO',
  CLICK_LEGIT_FILTER: 'CLICK_LEGIT_FILTER'
};

const welcome = {
  VIEW_WELCOME: 'VIEW_WELCOME',
  CLICK_PERSONAL_INPUT: 'CLICK_PERSONAL_INPUT',
  VIEW_PERSONAL_INPUT: 'VIEW_PERSONAL_INPUT',
  SELECT_ITEM: 'SELECT_ITEM',
  SUBMIT_PERSONAL_INPUT: 'SUBMIT_PERSONAL_INPUT'
};

const searchHelper = {
  VIEW_SEARCHHELPER: 'VIEW_SEARCHHELPER',
  CLICK_SEARCHHELPER: 'CLICK_SEARCHHELPER',
  SELECT_SEARCHHELPER: 'SELECT_SEARCHHELPER',
  SUBMIT_SEARCHHELPER: 'SUBMIT_SEARCHHELPER',
  SELECT_ITEM: 'SELECT_ITEM',
  SELECT_OPTIONTAB: 'SELECT_OPTIONTAB',
  VIEW_SEARCHHELPER_POPUP: 'VIEW_SEARCHHELPER_POPUP',
  CLICK_SEARCHHELPER_POPUP: 'CLICK_SEARCHHELPER_POPUP',
  VIEW_LOGIN_POPUP: 'VIEW_LOGIN_POPUP',
  CLICK_LOGIN_POPUP: 'CLICK_LOGIN_POPUP',
  VIEW_SEARCHHELPER_STEP1: 'VIEW_SEARCHHELPER_STEP1',
  VIEW_SEARCHHELPER_STEP2: 'VIEW_SEARCHHELPER_STEP2',
  LOAD_MYLIST_SAVE: 'LOAD_MYLIST_SAVE'
};

const myPortfolio = {
  CLICK_MYPORTFOLIO_BANNER: 'CLICK_MYPORTFOLIO_BANNER',
  VIEW_MYPORTFOLIO: 'VIEW_MYPORTFOLIO',
  CLICK_RESERVATION: 'CLICK_RESERVATION',
  CLICK_APPDOWNLOAD: 'CLICK_APPDOWNLOAD',
  CLICK_BACK: 'CLICK_BACK',
  CLICK_LOGO: 'CLICK_LOGO',
  VIEW_MYPORTFOLIO_MODAL: 'VIEW_MYPORTFOLIO_MODAL',
  CLICK_RESERVATION_LOGIN: 'CLICK_RESERVATION_LOGIN',
  VIEW_RESERVATION_COMPLETE_DIALOG: 'VIEW_RESERVATION_COMPLETE_DIALOG'
};

const legit = {
  VIEW_LEGIT_MAIN: 'VIEW_LEGIT_MAIN',
  CLICK_LEGIT_TAB: 'CLICK_LEGIT_TAB',
  CLICK_LEGIT_WISH: 'CLICK_LEGIT_WISH',
  CLICK_LEGIT_MODAL: 'CLICK_LEGIT_MODAL',
  CLICK_LEGIT_BRAND: 'CLICK_LEGIT_BRAND',
  CLICK_LEGIT_RESULT: 'CLICK_LEGIT_RESULT',
  CLICK_LOADMORE: 'CLICK_LOADMORE',
  CLICK_LEGIT_BANNER: 'CLICK_LEGIT_BANNER',
  VIEW_LEGIT_MY: 'VIEW_LEGIT_MY',
  CLICK_LEGIT_LIST: 'CLICK_LEGIT_LIST',
  CLICK_PRODUCT_DETAIL: 'CLICK_PRODUCT_DETAIL',
  VIEW_LEGIT_POPUP: 'VIEW_LEGIT_POPUP',
  VIEW_LEGIT_MODAL: 'VIEW_LEGIT_MODAL',
  VIEW_LEGIT_INFO: 'VIEW_LEGIT_INFO',
  CLICK_LEGIT_INFO: 'CLICK_LEGIT_INFO',
  VIEW_LEGIT_TOOLTIP: 'VIEW_LEGIT_TOOLTIP',
  CLICK_LEGIT_TOOLTIP: 'CLICK_LEGIT_TOOLTIP',
  VIEW_LEGIT_WISH: 'VIEW_LEGIT_WISH'
};

const legitResult = {
  VIEW_LEGIT_SURVEY: 'VIEW_LEGIT_SURVEY',
  SUBMIT_LEGIT_SURVEY: 'SUBMIT_LEGIT_SURVEY'
};

const legitGuide = {
  VIEW_LEGIT_POPUP: 'VIEW_LEGIT_POPUP',
  CLICK_LEGIT_BRAND: 'CLICK_LEGIT_BRAND'
};

const attrKeys = {
  sendLogApiEvent,
  appsFlyerEvent,
  naverEvent,
  commonEvent,
  login,
  brand,
  search,
  userInput,
  mypage,
  header,
  wishes,
  noti,
  sellerInfo,
  products,
  productsKeyword,
  category,
  home,
  welcome,
  searchHelper,
  myPortfolio,
  legit,
  legitResult,
  legitGuide
};

export default attrKeys;
