const productName = {
  MAIN: 'MAIN',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  PRODUCT_LIST: 'PRODUCT_LIST',
  WISH_MODAL: 'WISH_MODAL',
  HONEYPRODUCT: 'HONEYPRODUCT',
  RECENT_LIST: 'RECENT_LIST',
  SELLER_PRODUCT: 'SELLER_PRODUCT',
  AUTH_PRODUCT: 'AUTH_PRODUCT',
  WISH_LIST: 'WISH_LIST',
  AUTH_LIST: 'AUTH_LIST',
  LIST_RELATED: 'LIST_RELATED',
  MAIN_WISH: 'MAIN_WISH',
  PICGALLERY: 'PICGALLERY',
  NOTI_LIST: 'NOTI_LIST',
  INFO: 'INFO',
  BUDGET: 'BUDGET',
  ADDRESS: 'ADDRESS',
  ANNOUNCE_DETAIL: 'ANNOUNCE_DETAIL',
  SEARCHMODAL: 'SEARCHMODAL',
  BRAND: 'BRAND',
  BRAND_LIST: 'BRAND_LIST',
  BRAND_SEARCH: 'BRAND_SEARCH',
  CATEGORY: 'CATEGORY',
  CRM: 'CRM',
  SEARCH: 'SEARCH',
  WELCOME: 'WELCOME',
  SIZE: 'SIZE',
  MY: 'MY',
  MYPORTFOLIO: 'MYPORTFOLIO',
  MYPORTFOLIO_MODAL: 'MYPORTFOLIO_MODAL',
  PRODUCT: 'PRODUCT',
  DIRECT: 'DIRECT',
  HISTORY: 'HISTORY',
  SEARCHHELPER: 'SEARCHHELPER',
  LEGIT_PRODUCT: 'LEGIT_PRODUCT',
  AUTO: 'AUTO',
  MANUAL: 'MANUAL',
  WISH_LEGIT: 'WISH_LEGIT',
  NOTICES: 'NOTICES'
};

const productTitle = {
  RELATED: 'RELATED',
  PERSONAL: 'PERSONAL',
  HONEYNOTI_LIST: 'HONEYNOTI_LIST',
  WISH_MODAL: 'WISH_MODAL',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  QUICKSEARCH: 'QUICKSEARCH',
  CAMEL: 'CAMEL',
  GENDER: 'GENDER',
  BIRTH: 'BIRTH',
  RECOMMEND: 'RECOMMEND',
  INPUT: 'INPUT',
  STEP01: 'STEP01',
  STEP09: 'STEP09',
  HEADER: 'HEADER',
  DETAIL: 'DETAIL',
  RECOMMTAG: 'RECOMMTAG',
  RECENT: 'RECENT',
  SCOPE: 'SCOPE',
  AUTO: 'AUTO',
  BANNERB: 'BANNERB',
  BANNERC: 'BANNERC',
  PARENT: 'PARENT',
  SUBPARENT: 'SUBPARENT',
  DEFAULT: 'DEFAULT',
  BEHAVIOR: 'BEHAVIOR',
  BRAND: 'BRAND',
  CATEGORY: 'CATEGORY',
  LIST: 'LIST',
  HONEYNOTI: 'HONEYNOTI',
  SEARCHHELPER: 'SEARCHHELPER',
  CTA: 'CTA',
  ABOUT_CTA: 'ABOUT_CTA',
  MIDDLE: 'MIDDLE',
  TOP: 'TOP',
  PRE_CONFIRM: 'PRE_CONFIRM',
  MYLIST: 'MYLIST',
  MYLIST_DELETE: 'MYLIST_DELETE',
  MONEY: 'MONEY',
  RECOMMFILTER: 'RECOMMFILTER',
  WISHPRODUCT: 'WISHPRODUCT'
};

const productSource = {
  PRODUCT_LIST: 'PRODUCT_LIST',
  PRODUCT_RELATED_LIST: 'PRODUCT_RELATED_LIST',
  LIST_RELATED: 'LIST_RELATED',
  MAIN_WISH: 'MAIN_WISH',
  MAIN_MYLIST: 'MAIN_MYLIST',
  MAIN_RECENT_LIST: 'MAIN_RECENT_LIST',
  MAIN_RECENT: 'MAIN_RECENT',
  MAIN_PERSONAL: 'MAIN_PERSONAL',
  MAIN_CAMEL: 'MAIN_CAMEL',
  MAIN_AI_RECOMM: 'MAIN_AI_RECOMM',
  DIRECT: 'DIRECT',
  WISH_LIST: 'WISH_LIST',
  RECENT_LIST: 'RECENT_LIST',
  SELLER_PRODUCT: 'SELLER_PRODUCT',
  AUTH_PRODUCT: 'AUTH_PRODUCT',
  AUTH_LIST: 'AUTH_LIST',
  HONEYNOTI_LIST: 'HONEYNOTI_LIST'
};

const productType = {
  INPUT: 'INPUT',
  ETC: 'ETC',
  GUIDED: 'GUIDED',
  CRM: 'CRM',
  HISTORY: 'HISTORY'
};

const legitName = {
  LEGIT: 'LEGIT',
  LEGIT_MAIN: 'LEGIT_MAIN',
  LEGIT_MY: 'LEGIT_MY',
  LEGIT_POPUP: 'LEGIT_POPUP',
  LEGIT_INFO: 'LEGIT_INFO'
};

const legitTitle = {
  LEGIT_CASE: 'LEGIT_CASE',
  JOIN_BTN: 'JOIN_BTN',
  HOWTO: 'HOWTO',
  LEGIT_PUSHALERT: 'LEGIT_PUSHALERT',
  WISH_TO_LEGIT: 'WISH_TO_LEGIT',
  WISHRECENT_LEGIT: 'WISHRECENT_LEGIT',
  LEGIT_CASE_FILTER: 'LEGIT_CASE_FILTER',
  LEGITRESULT_TOOLTIP: 'LEGITRESULT_TOOLTIP',
  LEGIT_SHARE: 'LEGIT_SHARE',
  LEGIT_VIDEO: 'LEGIT_VIDEO',
  BRAND: 'BRAND',
  MYLEGIT: 'MYLEGIT'
};

const legitSource = {
  LEGIT_TARGET: 'LEGIT_TARGET'
};

const legitType = {
  GUIDED: 'GUIDED',
  HOWTO: 'HOWTO',
  LEGIT_PUSHALERT: 'LEGIT_PUSHALERT',
  WISH_TO_LEGIT: 'WISH_TO_LEGIT',
  WISHRECENT_LEGIT: 'WISHRECENT_LEGIT',
  LEGIT_CASE_FILTER: 'LEGIT_CASE_FILTER',
  LEGITRESULT_TOOLTIP: 'LEGITRESULT_TOOLTIP',
  LEGIT_SHARE: 'LEGIT_SHARE',
  LEGIT_VIDEO: 'LEGIT_VIDEO',
  BRAND: 'BRAND',
  MYLEGIT: 'MYLEGIT'
};

const name = {
  crazyWeek: 'CRAZY_WEEK',
  swipeXTag: 'SWIPE_X_TAG',
  popup: 'POPUP',
  list: 'LIST',
  main: 'MAIN',
  productList: 'PRODUCT_LIST',
  crazyWeekPopup: 'CRAZYWEEK_POPUP',
  filterMapToast: 'FILTER_MAP_TOAST',
  productDetail: 'PRODUCT_DETAIL',
  filterModal: 'FILTER_MODAL',
  filterMapModal: 'FILTER_MAP_MODAL',
  myListPopup: 'MYLIST_POPUP',
  filter: 'FILTER'
};

const title = {
  katalk: 'KATALK',
  fb: 'FB',
  twitter: 'TWITTER',
  url: 'URL',
  quick: 'QUICK',
  rare: 'RARE',
  lowPrice: 'LOWPRICE',
  priceDefense: 'PRICE_DEFENSE',
  camping: 'CAMPING',
  padding: 'PADDING',
  bottom: 'BOTTOM',
  curationCard: 'CURATION_CARD',
  popup: 'POPUP',
  banner: 'BANNER',
  modal: 'MODAL',
  none: 'NONE',
  end: 'END',
  brand: 'BRAND',
  line: 'LINE',
  category: 'CATEGORY',
  season: 'SEASON',
  colorMaterial: 'COLOR+MATERIAL',
  empty: 'EMPTY',
  site: 'SITE',
  size: 'SIZE',
  gender: 'GENDER',
  price: 'PRICE',
  productList: 'PRODUCT_LIST',
  auto: 'AUTO',
  myListDelete: 'MYLIST_DELETE',
  color: 'COLOR',
  dynamicFilter: 'DYNAMIC_FILTER',
  all: 'ALL'
};

const source = {
  crazycuration: 'CRAZY_WEEK'
};

const type = {
  guide: 'GUIDED'
};

const attrProperty = {
  productName,
  productTitle,
  productSource,
  productType,
  legitName,
  legitTitle,
  legitSource,
  legitType,
  name,
  title,
  source,
  type
};

export default attrProperty;
