const productName = {
  MAIN: 'MAIN',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  PRODUCT_LIST: 'PRODUCT_LIST',
  WISH_MODAL: 'WISH_MODAL',
  HONEYPRODUCT: 'HONEYPRODUCT',
  RECENT_LIST: 'RECENT_LIST',
  SELLER_PRODUCT: 'SELLER_PRODUCT',
  AUTH_PRODUCT: 'AUTH_PRODUCT',
  WISH_LIST: 'WISH_LIST',
  AUTH_LIST: 'AUTH_LIST',
  LIST_RELATED: 'LIST_RELATED',
  MAIN_WISH: 'MAIN_WISH',
  MAIN_PERSONAL: 'MAIN_PERSONAL',
  MAIN_CAMEL: 'MAIN_CAMEL',
  PICGALLERY: 'PICGALLERY',
  NOTI_LIST: 'NOTI_LIST',
  INFO: 'INFO',
  BUDGET: 'BUDGET',
  ADDRESS: 'ADDRESS',
  ANNOUNCE_DETAIL: 'ANNOUNCE_DETAIL',
  SEARCHMODAL: 'SEARCHMODAL',
  BRAND_LIST: 'BRAND_LIST',
  CATEGORY: 'CATEGORY',
  CRM: 'CRM',
  SEARCH: 'SEARCH',
  WELCOME: 'WELCOME',
  SIZE: 'SIZE'
};

const productTitle = {
  RELATED: 'RELATED',
  PERSONAL: 'PERSONAL',
  HONEYNOTI_LIST: 'HONEYNOTI_LIST',
  WISH_MODAL: 'WISH_MODAL',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  QUICKSEARCH: 'QUICKSEARCH',
  CAMEL: 'CAMEL',
  GENDER: 'GENDER',
  BIRTH: 'BIRTH',
  RECOMMEND: 'RECOMMEND',
  INPUT: 'INPUT'
};

const productSource = {
  PRODUCT_LIST: 'PRODUCT_LIST',
  PRODUCT_RELATED_LIST: 'PRODUCT_RELATED_LIST',
  LIST_RELATED: 'LIST_RELATED',
  MAIN_WISH: 'MAIN_WISH',
  MAIN_PERSONAL: 'MAIN_PERSONAL',
  MAIN_CAMEL: 'MAIN_CAMEL',
  MAIN_AI_RECOMM: 'MAIN_AI_RECOMM',
  DIRECT: 'DIRECT',
  WISH_LIST: 'WISH_LIST',
  RECENT_LIST: 'RECENT_LIST',
  SELLER_PRODUCT: 'SELLER_PRODUCT',
  AUTH_PRODUCT: 'AUTH_PRODUCT',
  AUTH_LIST: 'AUTH_LIST',
  HONEYNOTI_LIST: 'HONEYNOTI_LIST'
};

const attrProperty = {
  productName,
  productTitle,
  productSource
};

export default attrProperty;
