const productName = {
  MAIN: 'MAIN',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  PRODUCT_LIST: 'PRODUCT_LIST',
  WISH_MODAL: 'WISH_MODAL',
  HONEYPRODUCT: 'HONEYPRODUCT',
  RECENT_LIST: 'RECENT_LIST',
  SELLER_PRODUCT: 'SELLER_PRODUCT',
  AUTH_PRODUCT: 'AUTH_PRODUCT',
  WISH_LIST: 'WISH_LIST',
  AUTH_LIST: 'AUTH_LIST',
  LIST_RELATED: 'LIST_RELATED',
  MAIN_WISH: 'MAIN_WISH',
  MAIN_PERSONAL: 'MAIN_PERSONAL',
  MAIN_CAMEL: 'MAIN_CAMEL',
  PICGALLERY: 'PICGALLERY',
  NOTI_LIST: 'NOTI_LIST',
  INFO: 'INFO',
  BUDGET: 'BUDGET',
  ADDRESS: 'ADDRESS',
  ANNOUNCE_DETAIL: 'ANNOUNCE_DETAIL',
  SEARCHMODAL: 'SEARCHMODAL',
  BRAND_LIST: 'BRAND_LIST',
  BRAND_SEARCH: 'BRAND_SEARCH',
  CATEGORY: 'CATEGORY',
  CRM: 'CRM',
  SEARCH: 'SEARCH',
  WELCOME: 'WELCOME',
  SIZE: 'SIZE',
  PRODUCT: 'PRODUCT',
  DIRECT: 'DIRECT',
  HISTORY: 'HISTORY',
  SEARCHHELPER: 'SEARCHHELPER',
  LEGIT_PRODUCT: 'LEGIT_PRODUCT'
};

const productTitle = {
  RELATED: 'RELATED',
  PERSONAL: 'PERSONAL',
  HONEYNOTI_LIST: 'HONEYNOTI_LIST',
  WISH_MODAL: 'WISH_MODAL',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  QUICKSEARCH: 'QUICKSEARCH',
  CAMEL: 'CAMEL',
  GENDER: 'GENDER',
  BIRTH: 'BIRTH',
  RECOMMEND: 'RECOMMEND',
  INPUT: 'INPUT',
  DETAIL: 'DETAIL',
  RECOMMTAG: 'RECOMMTAG',
  RECENT: 'RECENT',
  SCOPE: 'SCOPE',
  AUTO: 'AUTO',
  BANNERB: 'BANNERB',
  BANNERC: 'BANNERC',
  PARENT: 'PARENT',
  SUBPARENT: 'SUBPARENT',
  DEFAULT: 'DEFAULT',
  BEHAVIOR: 'BEHAVIOR',
  BRAND: 'BRAND',
  CATEGORY: 'CATEGORY',
  LIST: 'LIST',
  HONEYNOTI: 'HONEYNOTI',
  SEARCHHELPER: 'SEARCHHELPER',
  CTA: 'CTA',
  ABOUT_CTA: 'ABOUT_CTA',
  MIDDLE: 'MIDDLE',
  TOP: 'TOP',
  PRE_CONFIRM: 'PRE_CONFIRM',
  MYLIST: 'MYLIST'
};

const productSource = {
  PRODUCT_LIST: 'PRODUCT_LIST',
  PRODUCT_RELATED_LIST: 'PRODUCT_RELATED_LIST',
  LIST_RELATED: 'LIST_RELATED',
  MAIN_WISH: 'MAIN_WISH',
  MAIN_PERSONAL: 'MAIN_PERSONAL',
  MAIN_CAMEL: 'MAIN_CAMEL',
  MAIN_AI_RECOMM: 'MAIN_AI_RECOMM',
  DIRECT: 'DIRECT',
  WISH_LIST: 'WISH_LIST',
  RECENT_LIST: 'RECENT_LIST',
  SELLER_PRODUCT: 'SELLER_PRODUCT',
  AUTH_PRODUCT: 'AUTH_PRODUCT',
  AUTH_LIST: 'AUTH_LIST',
  HONEYNOTI_LIST: 'HONEYNOTI_LIST'
};

const productType = {
  INPUT: 'INPUT',
  ETC: 'ETC',
  GUIDED: 'GUIDED',
  CRM: 'CRM',
  HISTORY: 'HISTORY'
};

const legitName = {
  LEGIT_MAIN: 'LEGIT_MAIN',
  LEGIT_MY: 'LEGIT_MY',
  LEGIT_POPUP: 'LEGIT_POPUP'
};

const legitTitle = {
  LEGIT_CASE: 'LEGIT_CASE',
  JOIN_BTN: 'JOIN_BTN',
  HOWTO: 'HOWTO'
};

const attrProperty = {
  productName,
  productTitle,
  productSource,
  productType,
  legitName,
  legitTitle
};

export default attrProperty;
