export const BRANDS_BY_GENDER = {
  M: [
    { id: 216, name: '에어조던', nameEng: 'airjordan' },
    { id: 25, name: '스톤아일랜드', nameEng: 'stoneisland' },
    { id: 6, name: '구찌', nameEng: 'gucci' },
    { id: 32, name: '톰브라운', nameEng: 'thombrowne' },
    { id: 52, name: '롤렉스', nameEng: 'rolex' },
    { id: 125, name: '프라이탁', nameEng: 'freitag' },
    { id: 11, name: '루이비통', nameEng: 'louisvuitton' },
    { id: 51, name: '애플', nameEng: 'apple' },
    { id: 8, name: '나이키', nameEng: 'nike' },
    { id: 17, name: '무스너클', nameEng: 'mooseknuckles' },
    { id: 58, name: '아디다스', nameEng: 'adidas' },
    { id: 18, name: '발렌시아가', nameEng: 'balenciaga' },
    { id: 28, name: '오프화이트', nameEng: 'offwhite' },
    { id: 13, name: '메종마르지엘라', nameEng: 'maisonmargiela' },
    { id: 21, name: '버버리', nameEng: 'burberry' },
    { id: 16, name: '몽클레어', nameEng: 'moncler' },
    { id: 49, name: '스투시', nameEng: 'stussy' },
    { id: 53, name: '아미', nameEng: 'ami' },
    { id: 27, name: '알렉산더맥퀸', nameEng: 'alexandermcqueen' }
  ],
  F: [
    { id: 44, name: '샤넬', nameEng: 'chanel' },
    { id: 6, name: '구찌', nameEng: 'gucci' },
    { id: 11, name: '루이비통', nameEng: 'louisvuitton' },
    { id: 34, name: '디올', nameEng: 'dior' },
    { id: 42, name: '프라다', nameEng: 'prada' },
    { id: 8, name: '나이키', nameEng: 'nike' },
    { id: 125, name: '프라이탁', nameEng: 'freitag' },
    { id: 216, name: '에어조던', nameEng: 'airjordan' },
    { id: 24, name: '생로랑', nameEng: 'saintlaurent' },
    { id: 21, name: '버버리', nameEng: 'burberry' },
    { id: 51, name: '애플', nameEng: 'apple' },
    { id: 18, name: '발렌시아가', nameEng: 'balenciaga' },
    { id: 39, name: '에르메스', nameEng: 'hermes' },
    { id: 58, name: '아디다스', nameEng: 'adidas' },
    { id: 41, name: '펜디', nameEng: 'fendi' },
    { id: 38, name: '셀린느', nameEng: 'celine' },
    { id: 13, name: '메종마르지엘라', nameEng: 'maisonmargiela' },
    { id: 37, name: '미우미우', nameEng: 'miumiu' },
    { id: 7, name: '꼼데가르송', nameEng: 'commedesgarcons' }
  ],
  N: [
    { id: 216, name: '에어조던', nameEng: 'airjordan' },
    { id: 44, name: '샤넬', nameEng: 'chanel' },
    { id: 6, name: '구찌', nameEng: 'gucci' },
    { id: 25, name: '스톤아일랜드', nameEng: 'stoneisland' },
    { id: 52, name: '롤렉스', nameEng: 'rolex' },
    { id: 51, name: '애플', nameEng: 'apple' },
    { id: 34, name: '디올', nameEng: 'dior' },
    { id: 11, name: '루이비통', nameEng: 'louisvuitton' },
    { id: 125, name: '프라이탁', nameEng: 'freitag' },
    { id: 32, name: '톰브라운', nameEng: 'thombrowne' },
    { id: 29, name: '이지부스트', nameEng: 'yeezyboost' },
    { id: 42, name: '프라다', nameEng: 'prada' },
    { id: 18, name: '발렌시아가', nameEng: 'balenciaga' },
    { id: 21, name: '버버리', nameEng: 'burberry' },
    { id: 13, name: '메종마르지엘라', nameEng: 'maisonmargiela' },
    { id: 28, name: '오프화이트', nameEng: 'offwhite' },
    { id: 24, name: '생로랑', nameEng: 'saintlaurent' },
    { id: 16, name: '몽클레어', nameEng: 'moncler' }
  ]
};
